### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.preprocess'

### ISSUE THREAD

**Issue by dingfangyu** [Thinklab-SJTU/DP3#1]
> (base) ding@ding:~/Desktop/DP3$ python main.py -h
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from utils.statistic import dataset_statistic
  File "/home/ding/Desktop/DP3/utils/__init__.py", line 1, in <module>
    from .batch_iterator import PaddedBatchIterator
  File "/home/ding/Desktop/DP3/utils/batch_iterator.py", line 3, in <module>
    from .preprocess import load_sequences
ModuleNotFoundError: No module named 'utils.preprocess'

**Comment by Receiling** [comment]
This version is not the latest due to my negligence. This bug has been fixed.
